# Site settings
title: Rolando Ramos
email: rolandorramos@gmail.com
description: " | software engineer, problem solver, gamer, and recently a dad!"
baseurl: ""
url: "https://www.rolandoramos.tech"
destination: site
permalink: pretty
paginate: 5
paginate_path: "/page:num/"

# Build settings

include: [ 404.html, assets, dist ]
exclude: [ _aws, _docker, _scripts, node_modules, .babelrc, .eslintrc.json, .gitignore,
      Gemfile, Gemfile.lock, gulpfile.babel.js, npm-debug.log, package.json ]

# Post settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->