# Site settings
title: rolspace
email: rolandorramos@gmail.com
description: " | Rolando Ramos' personal blog"
baseurl: ""
url: "http://www.rolspace.com"
destination: site
permalink: pretty
paginate: 5
paginate_path: "/page:num/"

# Build settings

include: [ 404.html, assets, dist ]
exclude: [ .babelrc, .eslintrc.json, .gitignore, _docker, _temp, _less, _scripts, aws, node_modules,
			Gemfile, Gemfile.lock, package.json, gulpfile.babel.js ]

# Post settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->