# Site settings
title: rolspace
email: rolandorramos@gmail.com
description: " - on code, life, and everything"
baseurl: ""
url: "http://www.rolspace.com"
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
include: [ assets, 404.html ]
exclude: [ _less, _scripts, bower_components, node_modules, bower.json, package.json, gruntfile.js,
			gulpfile.js, rolspace.sublime-project, rolspace.sublime-workspace ]

# Post settings
excerpt_separator: <!--more-->
highlighter: pygments