# Site settings
title: rolspace
email: rolandorramos@gmail.com
description: " | Rolando Ramos' personal blog"
baseurl: ""
url: "http://www.rolspace.com"
destination: site
paginate: 5
paginate_path: "/page:num/"

# Build settings
markdown: kramdown
include: [ 404.html, assets, dist ]
exclude: [ .babelrc, .eslintrc.json, .gitignore, _docker, _temp, _less, _scripts, bower_components, node_modules,
			bower.json, package.json, gulpfile.babel.js, rolspace.sublime-project, rolspace.sublime-workspace ]

# Post settings
excerpt_separator: <!--more-->
highlighter: pygments

# Gems
gems: [jekyll-paginate]