# Site settings
title: Rolspace
email: rolandorramos@gmail.com
description: "...on life, the universe, and everything"
baseurl: ""
url: "http://www.rolspace.com"

# Build settings
markdown: kramdown
include: [ _assets ]
exclude: [ bower_components, node_modules, bower.json ]

# Post settings
excerpt_separator: "<!more>"